apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fiscal-dragonfly-go 
  janus-idp.io/tekton: fiscal-dragonfly-go
  backstage.io/kubernetes-id: fiscal-dragonfly-go
  backstage.io/kubernetes-namespace: flavius-e2e 
  app.kubernetes.io/part-of: fiscal-dragonfly-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  